library(tidyverse)
library(sf)

raw <- st_read("data/S_USA.WildScenicRiver_LN/S_USA.WildScenicRiver_LN.shp")

# Master lookup table to link WSR table on rivers.gov to the WSR shapefile:
wsr_lookup_enhanced <- st_read("data/S_USA.WildScenicRiver_LN/S_USA.WildScenicRiver_LN.shp") %>%
  st_drop_geometry() %>%
  select(WSR_RIVER_, MANAGING_E, STATE) %>%
  distinct() %>%
  mutate(
    standard_name = case_when(
      # Handle Big and Little Darby Creeks
      WSR_RIVER_ == "Big and Little Darby Creeks Wild and Scenic River" ~ "Big and Little Darby Creeks, Ohio",
      
      # Handle Salmon rivers by agency
      WSR_RIVER_ == "Salmon Wild and Scenic River" & MANAGING_E == "NPS" ~ "Salmon, Alaska",
      WSR_RIVER_ == "Salmon Wild and Scenic River" & MANAGING_E == "USFS" ~ "Salmon, Idaho",
      WSR_RIVER_ == "Salmon Wild and Scenic River" & MANAGING_E == "USFS, BLM" ~ "Salmon, Oregon",
      
      # Handle Owyhee rivers by state - FIXED
      WSR_RIVER_ == "Owyhee Wild and Scenic River" & STATE == "Idaho" ~ "Owyhee, Idaho",
      WSR_RIVER_ == "Owyhee Wild and Scenic River" & STATE == "Oregon" ~ "Owyhee, Oregon",
      WSR_RIVER_ == "North Fork Owyhee Wild and Scenic River" & STATE == "Idaho" ~ "Owyhee (North Fork), Idaho",
      WSR_RIVER_ == "North Fork Owyhee Wild and Scenic River" & STATE == "Oregon" ~ "Owyhee (North Fork), Oregon",
      
      # All other mappings (keep everything else the same as before)
      WSR_RIVER_ == "Middle Fork Clearwater, Idaho Wild and Scenic River" ~ "Clearwater (Middle Fork), Idaho",
      WSR_RIVER_ == "Chattooga Wild and Scenic River" ~ "Chattooga, Georgia, North Carolina & South Carolina",
      WSR_RIVER_ == "Sandy Wild and Scenic River" ~ "Sandy, Oregon",
      WSR_RIVER_ == "South Fork John Day Wild and Scenic River" ~ "John Day (South Fork), Oregon",
      WSR_RIVER_ == "Whychus Creek Wild and Scenic River" ~ "Whychus Creek, Oregon",
      WSR_RIVER_ == "Sycan Wild and Scenic River" ~ "Sycan, Oregon",
      WSR_RIVER_ == "Rogue Wild and Scenic River" & MANAGING_E == "USFS" ~ "Rogue (Upper), Oregon",
      WSR_RIVER_ == "Rogue Wild and Scenic River" ~ "Rogue Oregon",
      WSR_RIVER_ == "Wenaha Wild and Scenic River" ~ "Wenaha, Oregon",
      WSR_RIVER_ == "West Little Owyhee Wild and Scenic River" ~ "West Little Owyhee, Oregon",
      WSR_RIVER_ == "White Wild and Scenic River" ~ "White, Oregon",
      WSR_RIVER_ == "Rio Chama Wild and Scenic River" ~ "Rio Chama, New Mexico",
      WSR_RIVER_ == "East Fork Jemez Wild and Scenic River" ~ "Jemez (East Fork), New Mexico",
      WSR_RIVER_ == "Rapid Wild and Scenic River" ~ "Rapid, Idaho",
      WSR_RIVER_ == "Pecos Wild and Scenic River" ~ "Pecos, New Mexico",
      WSR_RIVER_ == "Smith Wild and Scenic River" ~ "Smith, California",
      WSR_RIVER_ == "Clarks Fork Wild and Scenic River" ~ "Yellowstone (Clarks Fork), Wyoming",
      WSR_RIVER_ == "Niobrara Wild and Scenic River" ~ "Niobrara, Nebraska",
      WSR_RIVER_ == "Missouri Wild and Scenic River" ~ "Missouri River, Montana & Nebraska & South Dakota",
      WSR_RIVER_ == "Bear Creek Wild and Scenic River" ~ "Bear Creek, Michigan",
      WSR_RIVER_ == "Snake Wild and Scenic River" ~ "Snake, Idaho & Oregon",
      WSR_RIVER_ == "Black Wild and Scenic River" ~ "Black, Michigan",
      WSR_RIVER_ == "Carp Wild and Scenic River" ~ "Carp, Michigan",
      WSR_RIVER_ == "Indian Wild and Scenic River" ~ "Indian, Michigan",
      WSR_RIVER_ == "Manistee Wild and Scenic River" ~ "Manistee, Michigan",
      WSR_RIVER_ == "Ontonagon Wild and Scenic River" ~ "Ontonagon, Michigan",
      WSR_RIVER_ == "Paint Wild and Scenic River" ~ "Paint, Michigan",
      WSR_RIVER_ == "Pine Wild and Scenic River" ~ "Pine, Michigan",
      WSR_RIVER_ == "Presque Isle Wild and Scenic River" ~ "Presque Isle, Michigan",
      WSR_RIVER_ == "Sturgeon (Hiawatha National Forest) Wild and Scenic River" ~ "Sturgeon (Hiawatha National Forest), Michigan",
      WSR_RIVER_ == "Sturgeon (Ottawa National Forest) Wild and Scenic River" ~ "Sturgeon (Ottawa National Forest), Michigan",
      WSR_RIVER_ == "Flathead Wild and Scenic River" ~ "Flathead, Montana",
      WSR_RIVER_ == "East Branch Tahquamenon Wild and Scenic River" ~ "Tahquamenon (East Branch), Michigan",
      WSR_RIVER_ == "Whitefish Wild and Scenic River" ~ "Whitefish, Michigan",
      WSR_RIVER_ == "Yellow Dog Wild and Scenic River" ~ "Yellow Dog, Michigan",
      WSR_RIVER_ == "Allegheny Wild and Scenic River" ~ "Allegheny, Pennsylvania",
      WSR_RIVER_ == "Big Piney Creek Wild and Scenic River" ~ "Big Piney Creek, Arkansas",
      WSR_RIVER_ == "Buffalo Wild and Scenic River" ~ "Buffalo, Arkansas",
      WSR_RIVER_ == "Cossatot Wild and Scenic River" ~ "Cossatot, Arkansas",
      WSR_RIVER_ == "Hurricane Creek Wild and Scenic River" ~ "Hurricane Creek, Arkansas",
      WSR_RIVER_ == "Little Missouri Wild and Scenic River" ~ "Little Missouri, Arkansas",
      WSR_RIVER_ == "Mulberry Wild and Scenic River" ~ "Mulberry, Arkansas",
      WSR_RIVER_ == "North Sylamore Creek Wild and Scenic River" ~ "North Sylamore Creek, Arkansas",
      WSR_RIVER_ == "Richland Creek Wild and Scenic River" ~ "Richland Creek, Arkansas",
      WSR_RIVER_ == "Sespe Creek Wild and Scenic River" ~ "Sespe Creek, California",
      WSR_RIVER_ == "Sudbury, Assabet and Concord Wild and Scenic River" ~ "Sudbury, Assabet, Concord, Massachusetts",
      WSR_RIVER_ == "Wilson Creek Wild and Scenic River" ~ "Wilson Creek, North Carolina",
      WSR_RIVER_ == "Wekiva Wild and Scenic River" ~ "Wekiva, Florida",
      WSR_RIVER_ == "White Clay Wild and Scenic River" ~ "White Clay Creek, Delaware & Pennsylvania",
      WSR_RIVER_ == "Wildhorse and Kinger Creeks Wild and Scenic River" ~ "Wildhorse and Kiger Creeks, Oregon",
      WSR_RIVER_ == "Delaware (Lower) Wild and Scenic River" ~ "Delaware River, New York & New Jersey & Pennsylvania",
      WSR_RIVER_ == "Delaware (Middle) Wild and Scenic River" ~ "Delaware River, New York & New Jersey & Pennsylvania",
      WSR_RIVER_ == "Delaware (Upper) Wild and Scenic River" ~ "Delaware River, New York & New Jersey & Pennsylvania",
      WSR_RIVER_ == "Rio Mameyes Wild and Scenic River" ~ "Rio Mameyes, Puerto Rico",
      WSR_RIVER_ == "Rio De La Mina Wild and Scenic River" ~ "Rio de la Mina, Puerto Rico",
      WSR_RIVER_ == "Rio Icacos Wild and Scenic River" ~ "Rio Icacos, Puerto Rico",
      WSR_RIVER_ == "White Salmon Wild and Scenic River" ~ "White Salmon, Washington",
      WSR_RIVER_ == "Black Butte Wild and Scenic River" ~ "Black Butte, California",
      WSR_RIVER_ == "Musconetcong Wild and Scenic River" ~ "Musconetcong, New Jersey",
      WSR_RIVER_ == "Rio Grande Wild and Scenic River" ~ "Rio Grande, New Mexico & Texas",
      WSR_RIVER_ == "Rio Grande, New Mexico Wild and Scenic River" ~ "Rio Grande, New Mexico & Texas",
      WSR_RIVER_ == "Eightmile Wild and Scenic River" ~ "Eightmile, Connecticut",
      WSR_RIVER_ == "South Fork Clackamas Wild and Scenic River" ~ "Clackamas (South Fork), Oregon",
      WSR_RIVER_ == "Eagle Creek (Mt Hood) Wild and Scenic River" ~ "Eagle Creek (Mt. Hood), Oregon",
      WSR_RIVER_ == "Middle Fork Hood Wild and Scenic River" ~ "Hood (Middle Fork), Oregon",
      WSR_RIVER_ == "South Fork Roaring Wild and Scenic River" ~ "Roaring (South Fork), Oregon",
      WSR_RIVER_ == "Zig Zag Wild and Scenic River" ~ "Zigzag, Oregon",
      WSR_RIVER_ == "Fifteenmile Creek Wild and Scenic River" ~ "Fifteenmile Creek, Oregon",
      WSR_RIVER_ == "East Fork Hood Wild and Scenic River" ~ "Hood (East Fork), Oregon",
      WSR_RIVER_ == "Collawash Wild and Scenic River" ~ "Collawash, Oregon",
      WSR_RIVER_ == "Fish Creek Wild and Scenic River" ~ "Fish Creek, Oregon",
      WSR_RIVER_ == "Skagit Wild and Scenic River" ~ "Skagit, Washington",
      WSR_RIVER_ == "Battle Creek Wild and Scenic River" ~ "Battle Creek, Idaho",
      WSR_RIVER_ == "Big Jacks Creek , Idaho Wild and Scenic River" ~ "Big Jacks Creek, Idaho",
      WSR_RIVER_ == "Bruneau, Idaho Wild and Scenic River" ~ "Bruneau, Idaho",
      WSR_RIVER_ == "West Fork Bruneau, Idaho Wild and Scenic River" ~ "Bruneau (West Fork), Idaho",
      WSR_RIVER_ == "Sisquoc Wild and Scenic River" ~ "Sisquoc, California",
      WSR_RIVER_ == "Big Sur Wild and Scenic River" ~ "Big Sur, California",
      WSR_RIVER_ == "Great Egg Harbor Wild and Scenic River" ~ "Great Egg Harbor, New Jersey",
      WSR_RIVER_ == "Maurice Wild and Scenic River" ~ "Maurice, New Jersey",
      WSR_RIVER_ == "Obed Wild and Scenic River" ~ "Obed, Tennessee",
      WSR_RIVER_ == "Red Wild and Scenic River" ~ "Red, Kentucky",
      WSR_RIVER_ == "West Branch Farmington Wild and Scenic River" ~ "Farmington (West Branch), Connecticut",
      WSR_RIVER_ == "Clarion Wild and Scenic River" ~ "Clarion, Pennsylvania",
      WSR_RIVER_ == "Lamprey Wild and Scenic River" ~ "Lamprey, New Hampshire",
      WSR_RIVER_ == "Elkhorn Creek Wild and Scenic River" ~ "Elkhorn Creek, Oregon",
      WSR_RIVER_ == "Pere Marquette Wild and Scenic River" ~ "Pere Marquette, Michigan",
      WSR_RIVER_ == "Piru Creek Wild and Scenic River" ~ "Piru Creek, California",
      WSR_RIVER_ == "Eleven Point Wild and Scenic River" ~ "Eleven Point, Missouri",
      WSR_RIVER_ == "North Fork San Jacinto Wild and Scenic River" ~ "San Jacinto (North Fork), California",
      WSR_RIVER_ == "Fuller Mill Creek Wild and Scenic River" ~ "Fuller Mill Creek, California",
      WSR_RIVER_ == "Palm Canyon Creek Wild and Scenic River" ~ "Palm Canyon Creek, California",
      WSR_RIVER_ == "Bautista Creek Wild and Scenic River" ~ "Bautista Creek, California",
      WSR_RIVER_ == "Virgin Wild and Scenic River" ~ "Virgin, Utah",
      WSR_RIVER_ == "Fossil Creek Wild and Scenic River" ~ "Fossil Creek, Arizona",
      WSR_RIVER_ == "Snake River Headwaters Wild and Scenic River" ~ "Snake River Headwaters, Wyoming",
      WSR_RIVER_ == "Taunton Wild and Scenic River" ~ "Taunton, Massachusetts",
      WSR_RIVER_ == "River Styx Wild and Scenic River" ~ "River Styx (Cave Creek), Oregon",
      WSR_RIVER_ == "Middle Fork Snoqualmie Wild and Scenic River" ~ "Snoqualmie (Middle Fork), Washington",
      WSR_RIVER_ == "North Fork American Wild and Scenic River" ~ "American (North Fork), California",
      WSR_RIVER_ == "Pratt Wild and Scenic River" ~ "Pratt, Washington",
      WSR_RIVER_ == "Illabot Wild and Scenic River" ~ "Illabot Creek, Washington",
      WSR_RIVER_ == "Missisquoi & Trout Wild and Scenic River" ~ "Missisquoi & Trout, Vermont",
      WSR_RIVER_ == "East Rosebud Creek Wild and Scenic River" ~ "East Rosebud Creek, Montana",
      WSR_RIVER_ == "Franklin Creek Wild and Scenic River" ~ "Franklin Creek, Oregon",
      WSR_RIVER_ == "Wasson Wild and Scenic River" ~ "Wasson Creek, Oregon",
      WSR_RIVER_ == "Molalla Wild and Scenic River" ~ "Molalla, Oregon",
      WSR_RIVER_ == "Nestucca Wild and Scenic River" ~ "Nestucca, Oregon",
      WSR_RIVER_ == "Walker Creek Wild and Scenic River" ~ "Walker Creek, Oregon",
      WSR_RIVER_ == "North Fork Silver Creek Wild and Scenic River" ~ "North Fork Silver Creek, Oregon",
      WSR_RIVER_ == "Jenny Creek Wild and Scenic River" ~ "Jenny Creek, Oregon",
      WSR_RIVER_ == "Spring Creek Wild and Scenic River" ~ "Spring Creek, Oregon",
      WSR_RIVER_ == "Lobster Creek Wild and Scenic River" ~ "Lobster Creek, Oregon",
      WSR_RIVER_ == "Elk Creek Wild and Scenic River" ~ "Elk Creek, Oregon",
      WSR_RIVER_ == "Green Wild and Scenic River" ~ "Green, Utah",
      WSR_RIVER_ == "Lower Farmington River and Salmon Brook Wild and Scenic River" ~ "Farmington & Salmon Brook, Connecticut",
      WSR_RIVER_ == "Wood-Pawcatuck Watershed Wild and Scenic River" ~ "Wood-Pawcatuck Watershed, Connecticut/RI",
      WSR_RIVER_ == "Nashua,Squannacook,and Nissitissit Wild and Scenic Rivers" ~ "Nashua, Massachusetts & New Hampshire",
      WSR_RIVER_ == "Merced Wild and Scenic River" ~ "Merced, California",
      WSR_RIVER_ == "Cottonwood Creek, Idaho Wild and Scenic River" ~ "Cottonwood Creek, Idaho",
      WSR_RIVER_ == "Deep Creek, Idaho Wild and Scenic River" ~ "Deep Creek, Idaho",
      WSR_RIVER_ == "Dickshoot Creek, Idaho Wild and Scenic River" ~ "Dickshooter Creek, Idaho",
      WSR_RIVER_ == "Duncan Creek, Idaho Wild and Scenic River" ~ "Duncan Creek, Idaho",
      WSR_RIVER_ == "Jarbidge Wild and Scenic River" ~ "Jarbidge, Idaho",
      WSR_RIVER_ == "Little Jacks Creek Wild and Scenic River" ~ "Little Jacks Creek, Idaho",
      WSR_RIVER_ == "South Fork Owyhee Wild and Scenic River" ~ "Owyhee (South Fork), Idaho",
      WSR_RIVER_ == "Wickahoney Creek Wild and Scenic River" ~ "Wickahoney Creek, Idaho",
      WSR_RIVER_ == "Amargosa Wild and Scenic River" ~ "Amargosa, California",
      WSR_RIVER_ == "Owens River Headwaters Wild and Scenic River" ~ "Owens River Headwaters, California",
      WSR_RIVER_ == "Cottonwood Creek Wild and Scenic River" ~ "Cottonwood Creek, California",
      WSR_RIVER_ == "Kings Wild and Scenic River" ~ "Kings, California",
      WSR_RIVER_ == "Kern Wild and Scenic River" ~ "Kern, California",
      WSR_RIVER_ == "Bluestone Wild and Scenic River" ~ "Bluestone, West Virginia",
      WSR_RIVER_ == "Sipsey Fork of the West Fork Wild and Scenic River" ~ "Sipsey Fork West Fork, Alabama",
      WSR_RIVER_ == "Wildcate Wild and Scenic River" ~ "Wildcat, New Hampshire",
      WSR_RIVER_ == "Big Marsh Creek Wild and Scenic River" ~ "Big Marsh Creek, Oregon",
      WSR_RIVER_ == "Chetco Wild and Scenic River" ~ "Chetco, Oregon",
      WSR_RIVER_ == "Middle Fork Salmon Wild and Scenic River" ~ "Salmon (Middle Fork), Idaho",
      WSR_RIVER_ == "Clackamas Wild and Scenic River" ~ "Clackamas, Oregon",
      WSR_RIVER_ == "Crescent Creek Wild and Scenic River" ~ "Crescent Creek, Oregon",
      WSR_RIVER_ == "Crooked Wild and Scenic River" ~ "Crooked, Oregon",
      WSR_RIVER_ == "Deschutes Wild and Scenic River" ~ "Deschutes, Oregon",
      WSR_RIVER_ == "Donner und Blitzen Wild and Scenic River" ~ "Donner und Blitzen, Oregon",
      WSR_RIVER_ == "Eagle Creek (Wallowa-Whitman) Wild and Scenic River" ~ "Eagle Creek, Oregon (Wallowa-Whitman)",
      WSR_RIVER_ == "Elk Wild and Scenic River" ~ "Elk, Oregon",
      WSR_RIVER_ == "Grande Ronde Wild and Scenic River" ~ "Grande Ronde, Oregon",
      WSR_RIVER_ == "Imnaha Wild and Scenic River" ~ "Imnaha, Oregon",
      WSR_RIVER_ == "John Day Wild and Scenic River" ~ "John Day, Oregon",
      WSR_RIVER_ == "Wolf Wild and Scenic River" ~ "Wolf, Wisconsin",
      WSR_RIVER_ == "Joseph Creek Wild and Scenic River" ~ "Joseph Creek, Oregon",
      WSR_RIVER_ == "Surprise Canyon Creek Wild and Scenic River" ~ "Surprise Canyon Creek, California",
      WSR_RIVER_ == "Deep Creek Wild and Scenic River" ~ "Deep Creek, California",
      WSR_RIVER_ == "Saint Joe Wild and Scenic River" ~ "Saint Joe, Idaho",
      WSR_RIVER_ == "Whitewater Wild and Scenic River" ~ "Whitewater River, California",
      WSR_RIVER_ == "York Wild and Scenic River" ~ "Farmington (West Branch), Connecticut",
      WSR_RIVER_ == "Housatonic Wild and Scenic River" ~ "Farmington (West Branch), Connecticut",
      WSR_RIVER_ == "Alagnak Wild and Scenic River" ~ "Alagnak, Alaska",
      WSR_RIVER_ == "Alatna Wild and Scenic River" ~ "Alatna, Alaska",
      WSR_RIVER_ == "Aniakchak Wild and Scenic River" ~ "Aniakchak, Alaska",
      WSR_RIVER_ == "Charley Wild and Scenic River" ~ "Charley, Alaska",
      WSR_RIVER_ == "Chilikadrotna Wild and Scenic River" ~ "Chilikadrotna, Alaska",
      WSR_RIVER_ == "Feather Wild and Scenic River" ~ "Feather, California",
      WSR_RIVER_ == "John Wild and Scenic River" ~ "John, Alaska",
      WSR_RIVER_ == "Kobuk Wild and Scenic River" ~ "Kobuk, Alaska",
      WSR_RIVER_ == "Mulchatna Wild and Scenic River" ~ "Mulchatna, Alaska",
      WSR_RIVER_ == "Noatak Wild and Scenic River" ~ "Noatak, Alaska",
      WSR_RIVER_ == "North Fork Koyukuk Wild and Scenic River" ~ "Koyukuk (North Fork), Alaska",
      WSR_RIVER_ == "Tinayguk Wild and Scenic River" ~ "Tinayguk, Alaska",
      WSR_RIVER_ == "Tlikakila Wild and Scenic River" ~ "Tlikakila, Alaska",
      WSR_RIVER_ == "Andreafsky Wild and Scenic River" ~ "Andreafsky, Alaska",
      WSR_RIVER_ == "Ivishak Wild and Scenic River" ~ "Ivishak, Alaska",
      WSR_RIVER_ == "Nowitna Wild and Scenic River" ~ "Nowitna, Alaska",
      WSR_RIVER_ == "Selawik Wild and Scenic River" ~ "Selawik, Alaska",
      WSR_RIVER_ == "Sheenjek Wild and Scenic River" ~ "Sheenjek, Alaska",
      WSR_RIVER_ == "Wind Wild and Scenic River" ~ "Wind, Alaska",
      WSR_RIVER_ == "Beaver Wild and Scenic River" ~ "Beaver Creek, Alaska",
      WSR_RIVER_ == "Birch Creek Wild and Scenic River" ~ "Birch Creek, Alaska",
      WSR_RIVER_ == "Delta Wild and Scenic River" ~ "Delta, Alaska",
      WSR_RIVER_ == "Fortymile Wild and Scenic River" ~ "Fortymile, Alaska",
      WSR_RIVER_ == "Gulkana Wild and Scenic River" ~ "Gulkana, Alaska",
      WSR_RIVER_ == "Red Canyon Wild and Scenic River" ~ "Red Canyon, Idaho",
      WSR_RIVER_ == "Sheep Creek Wild and Scenic River" ~ "Sheep Creek, Idaho",
      WSR_RIVER_ == "Unalakleet Wild and Scenic River" ~ "Unalakleet, Alaska",
      WSR_RIVER_ == "Verde Wild and Scenic River" ~ "Verde, Arizona",
      WSR_RIVER_ == "Au Sable Wild and Scenic River" ~ "Au Sable, Michigan",
      WSR_RIVER_ == "Tuolumne Wild and Scenic River" ~ "Tuolumne, California",
      WSR_RIVER_ == "Illinois Wild and Scenic River" ~ "Illinois, Oregon",
      WSR_RIVER_ == "Horsepasture Wild and Scenic River" ~ "Horsepasture, North Carolina",
      WSR_RIVER_ == "Cache la Poudre Wild and Scenic River" ~ "Cache la Poudre, Colorado",
      WSR_RIVER_ == "Saline Bayou Wild and Scenic River" ~ "Saline Bayou, Louisiana",
      WSR_RIVER_ == "Black Creek Wild and Scenic River" ~ "Black Creek, Mississippi",
      WSR_RIVER_ == "St. Croix Wild and Scenic River" ~ "St. Croix River, Minnesota & Wisconsin",
      WSR_RIVER_ == "Klickitat Wild and Scenic River" ~ "Klickitat, Washington",
      WSR_RIVER_ == "North Fork Smith Wild and Scenic River" ~ "Smith (North Fork), Oregon",
      WSR_RIVER_ == "North Fork Sprague Wild and Scenic River" ~ "Sprague (North Fork), Oregon",
      WSR_RIVER_ == "North Powder Wild and Scenic River" ~ "North Powder, Oregon",
      WSR_RIVER_ == "North Umpqua Wild and Scenic River" ~ "North Umpqua, Oregon",
      WSR_RIVER_ == "Quartzville Creek Wild and Scenic River" ~ "Quartzville Creek, Oregon",
      WSR_RIVER_ == "Powder Wild and Scenic River" ~ "Powder, Oregon",
      WSR_RIVER_ == "Roaring Wild and Scenic River" ~ "Roaring, Oregon",
      WSR_RIVER_ == "Allagash Wild and Scenic River" ~ "Allagash Wilderness Waterway, Maine",
      WSR_RIVER_ == "Trinity Wild and Scenic River" ~ "Trinity, California",
      WSR_RIVER_ == "Loxahatchee Wild and Scenic River" ~ "Loxahatchee, Florida",
      WSR_RIVER_ == "Middle Fork Vermilion Wild and Scenic River" ~ "Vermilion (Middle Fork), Illinois",
      WSR_RIVER_ == "Westfield Wild and Scenic River" ~ "Westfield, Massachusetts",
      WSR_RIVER_ == "Klamath Wild and Scenic River" ~ "Klamath River, Oregon & California",
      WSR_RIVER_ == "Wallowa Wild and Scenic River" ~ "Wallowa, Oregon",
      WSR_RIVER_ == "Lumber Wild and Scenic River" ~ "Lumber, North Carolina",
      WSR_RIVER_ == "Little Miami Wild and Scenic River" ~ "Little Miami, Ohio",
      WSR_RIVER_ == "Little Beaver Creek Wild and Scenic River" ~ "Little Beaver, Ohio",
      WSR_RIVER_ == "New Wild and Scenic River" ~ "New, North Carolina",
      WSR_RIVER_ == "Little Deschutes Wild and Scenic River" ~ "Little Deschutes, Oregon",
      WSR_RIVER_ == "Lostine Wild and Scenic River" ~ "Lostine, Oregon",
      WSR_RIVER_ == "Malheur Wild and Scenic River" ~ "Malheur, Oregon",
      WSR_RIVER_ == "McKenzie Wild and Scenic River" ~ "McKenzie, Oregon",
      WSR_RIVER_ == "Metolius Wild and Scenic River" ~ "Metolius, Oregon",
      WSR_RIVER_ == "Minam Wild and Scenic River" ~ "Minam, Oregon",
      WSR_RIVER_ == "North Fork Crooked Wild and Scenic River" ~ "Crooked (North Fork), Oregon",
      WSR_RIVER_ == "North Fork John Day Wild and Scenic River" ~ "John Day (North Fork), Oregon",
      WSR_RIVER_ == "North Fork Malheur Wild and Scenic River" ~ "Malheur (North Fork), Oregon",
      WSR_RIVER_ == "North Fork Middle Fork Willamette Wild and Scenic River" ~ "Willamette (North Fork Middle Fork), Oregon",
      WSR_RIVER_ == "Lower American Wild and Scenic River" ~ "American (Lower), California",
      WSR_RIVER_ == "Eel Wild and Scenic River" ~ "Eel, California",
      TRUE ~ NA_character_
    )
  ) %>%
  mutate(WSR_RIVER_ = ifelse(WSR_RIVER_ == "Rogue Wild and Scenic River" & MANAGING_E == "USFS", 
                             "Rogue (Upper) Wild and Scenic River", WSR_RIVER_)) 

# "Dissolve" the lines into each WSR listed on rivers.gov master table 
wsr_dissolved <- st_read("data/S_USA.WildScenicRiver_LN/S_USA.WildScenicRiver_LN.shp") %>%
   # Upper Rogue not differentiated in the shapefile
  mutate(WSR_RIVER_ = ifelse(WSR_RIVER_ == "Rogue Wild and Scenic River" & MANAGING_E == "USFS", 
                             "Rogue (Upper) Wild and Scenic River", WSR_RIVER_)) %>%
  left_join(wsr_lookup_enhanced, by = c("WSR_RIVER_", "MANAGING_E", "STATE")) %>%
  filter(!is.na(standard_name)) %>%
  group_by(standard_name) %>%
  summarize(geometry = st_union(geometry), .groups = "drop")

# Test - any missing or are there too many? Should equal 226.
n_distinct(wsr_dissolved$standard_name)

saveRDS(wsr_dissolved, "data/wsr_official_lines.RDS")
